\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{siunitx}
\usepackage{amssymb} % for math symbols
\usepackage{amsmath} % for aligning equations
\usepackage{textcomp}
\usepackage{mdframed}
\usepackage{natbib}
\bibliographystyle{..//references/styles/besjournals.bst}
\usepackage[small]{caption}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%\pagestyle{empty} %comment if want page numbers
\parskip 7.2pt
\renewcommand{\baselinestretch}{1.5}
\parindent 0pt
%\usepackage{lineno}
%\linenumbers

%cross referencing:
\usepackage{xr}
\externaldocument{chillfrz_supp}

\newmdenv[
  topline=true,
  bottomline=true,
  skipabove=\topsep,
  skipbelow=\topsep
]{siderules}

%% R Script
<<label=libraries, echo=FALSE, results="asis", message=FALSE, warning=FALSE>>=
  options(stringsAsFactors=FALSE)
library(dplyr)
library(tidyr)
library(ggplot2)
@

\begin{document}

\noindent \textbf{\Large{False spring damage on temperate tree seedlings is amplified with winter warming}}

\noindent Authors:\\
C. J. Chamberlain $^{1,2}$, K. Woodruff $^{1}$ \& E. M. Wolkovich $^{1,2,3}$
\vspace{2ex}\\
\emph{Author affiliations:}\\
$^{1}$Arnold Arboretum of Harvard University, 1300 Centre Street, Boston, Massachusetts, USA; \\
$^{2}$Organismic \& Evolutionary Biology, Harvard University, 26 Oxford Street, Cambridge, Massachusetts, USA; \\
$^{3}$Forest \& Conservation Sciences, Faculty of Forestry, University of British Columbia, 2424 Main Mall, Vancouver, BC V6T 1Z4\\
\vspace{2ex}
$^*$Corresponding author: 248.953.0189; cchamberlain@g.harvard.edu\\

\renewcommand{\thetable}{\arabic{table}}
\renewcommand{\thefigure}{\arabic{figure}}
\renewcommand{\labelitemi}{$-$}
\setkeys{Gin}{width=0.8\textwidth}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<label=numbers, echo=FALSE, results="asis", warning=FALSE, message=FALSE,>>=
#load models and data to report numbers of things
options(stringsAsFactors = FALSE)
library(brms)

## Set Working Directory
setwd("~/Documents/git/chillfreeze/analyses/")

## load the model
load("stan/dvr_brms.Rdata")
load("stan/gslengthlo_brms_adjusted.Rdata") 
load("stan/meristem_brms.Rdata")

load("stan/chlavg_brms.Rdata")
load("stan/toughness_brms.Rdata")
load("stan/thickness_brms.Rdata")

load("stan/htdiff_brms.Rdata") 
load("stan/totbiomass_brms.Rdata")
load("stan/roottoshoot_brms.Rdata")

chillfrz <- read.csv("output/clean_dvr_traits.csv", header=TRUE)
rmspp <- c("NYSSYL", "FAGGRA")
chillfrz <- chillfrz[!(chillfrz$species%in%rmspp),]

### DVR Model - WITH ENOUGH CHILLING, CAN COMPENSATE FOR TX!!!
dvrtx<-round(mean(fixef(dvr.mod, pars="tx", summary=FALSE)), digits=2) ### 2.97
dvrtxsd<-round(sd(fixef(dvr.mod, pars="tx", summary=FALSE)), digits=2) # 0.97
dvrchill1<-round(mean(fixef(dvr.mod, pars="chill1", summary=FALSE)), digits=2) # -0.53
dvrchill1sd<-round(sd(fixef(dvr.mod, pars="chill1", summary=FALSE)), digits=2) # 1.38
dvrchill2<-round(mean(fixef(dvr.mod, pars="chill2", summary=FALSE)), digits=2) ### -2.67
dvrchill2sd<-round(sd(fixef(dvr.mod, pars="chill2", summary=FALSE)), digits=2) # 1.14

dvrtxchill1<-round(mean(fixef(dvr.mod, pars="tx:chill1", summary=FALSE)), digits=2) 
dvrtxchill1sd<-round(sd(fixef(dvr.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 1.14
dvrtxchill1 <- dvrtx + dvrchill1 + dvrtxchill1 ### 1.53

dvrtxchill2<-round(mean(fixef(dvr.mod, pars="tx:chill2", summary=FALSE)), digits=2) 
dvrtxchill2sd<-round(sd(fixef(dvr.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 1.08
dvrtxchill2 <- dvrtx + dvrchill2 + dvrtxchill2 # 0.92


### Gslength Model - CHILLING EXTENDS GS!!!! AND CAN COMPENSATE FOR TX!
gslengthtx<-round(mean(fixef(gslength.modlo, pars="tx", summary=FALSE)), digits=2) # -2.9
gslengthtxsd<-round(sd(fixef(gslength.modlo, pars="tx", summary=FALSE)), digits=2) # 5.52
gslengthchill1<-round(mean(fixef(gslength.modlo, pars="chill1", summary=FALSE)), digits=2) ### 3.11
gslengthchill1sd<-round(sd(fixef(gslength.modlo, pars="chill1", summary=FALSE)), digits=2) # 4.97
gslengthchill2<-round(mean(fixef(gslength.modlo, pars="chill2", summary=FALSE)), digits=2) ### -6.82
gslengthchill2sd<-round(sd(fixef(gslength.modlo, pars="chill2", summary=FALSE)), digits=2) # 5.11
gslengthtxchill1<-round(mean(fixef(gslength.modlo, pars="tx:chill1", summary=FALSE)), digits=2) 
gslengthtxchill1sd<-round(sd(fixef(gslength.modlo, pars="tx:chill1", summary=FALSE)), digits=2) # 6.63
gslengthtxchill1 <- gslengthtx + gslengthchill1 + gslengthtxchill1 # -13.91

gslengthtxchill2<-round(mean(fixef(gslength.modlo, pars="tx:chill2", summary=FALSE)), digits=2)
gslengthtxchill2sd<-round(sd(fixef(gslength.modlo, pars="tx:chill2", summary=FALSE)), digits=2) # 6.97
gslengthtxchill2 <- gslengthtx + gslengthchill2 + gslengthtxchill2 ### -19.08

### Meristem Model - MERISTEM DAMAGE ACROSS CHILL TXs!!
meritx<-round(mean(fixef(meri.mod, pars="tx", summary=FALSE)), digits=2) ### 2.07
meritxsd<-round(sd(fixef(meri.mod, pars="tx", summary=FALSE)), digits=2) # 0.97
merichill1<-round(mean(fixef(meri.mod, pars="chill1", summary=FALSE)), digits=2) # -0.53
merichill1sd<-round(sd(fixef(meri.mod, pars="chill1", summary=FALSE)), digits=2) # 1.88
merichill2<-round(mean(fixef(meri.mod, pars="chill2", summary=FALSE)), digits=2) # -0.18
merichill2sd<-round(sd(fixef(meri.mod, pars="chill2", summary=FALSE)), digits=2) # 1.17
meritxchill1<-round(mean(fixef(meri.mod, pars="tx:chill1", summary=FALSE)), digits=2) 
meritxchill1sd<-round(sd(fixef(meri.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 1.42
meritxchill1 <- meritx + merichill1 + meritxchill1 # 1.33

meritxchill2<-round(mean(fixef(meri.mod, pars="tx:chill2", summary=FALSE)), digits=2) 
meritxchill2sd<-round(sd(fixef(meri.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 1.31
meritxchill2 <- meritx + merichill2 + meritxchill2 ### 2.17

### Chlo Model ### PROBABLY MOVE TO SUPP!!! TX DECREASES CHLORO ESP WITH MORE CHILLING...
chltx<-round(mean(fixef(chl.mod, pars="tx", summary=FALSE)), digits=2) # -0.35
chltxsd<-round(sd(fixef(chl.mod, pars="tx", summary=FALSE)), digits=2) # 0.77
chlchill1<-round(mean(fixef(chl.mod, pars="chill1", summary=FALSE)), digits=2) # -0.06
chlchill1sd<-round(sd(fixef(chl.mod, pars="chill1", summary=FALSE)), digits=2) # 0.84
chlchill2<-round(mean(fixef(chl.mod, pars="chill2", summary=FALSE)), digits=2) # 0.43
chlchill2sd<-round(sd(fixef(chl.mod, pars="chill2", summary=FALSE)), digits=2) # 0.91
chltxchill1<-round(mean(fixef(chl.mod, pars="tx:chill1", summary=FALSE)), digits=2)
chltxchill1sd<-round(sd(fixef(chl.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 1.16
chltxchill1 <- chltx + chlchill1 + chltxchill1 ### -1.45

chltxchill2<-round(mean(fixef(chl.mod, pars="tx:chill2", summary=FALSE)), digits=2)
chltxchill2sd<-round(sd(fixef(chl.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 1.07
chltxchill2 <- chltx + chlchill2 + chltxchill2 ### -2.03

### Tough Model - TOUGHNESS DECREASES ACROSS ALL CHILL TXs!!!!
toughtx<-round(mean(fixef(toughness.mod, pars="tx", summary=FALSE)), digits=2) ### -0.05
toughtxsd<-round(sd(fixef(toughness.mod, pars="tx", summary=FALSE)), digits=2) # 0.02
toughchill1<-round(mean(fixef(toughness.mod, pars="chill1", summary=FALSE)), digits=2) ### -0.06
toughchill1sd<-round(sd(fixef(toughness.mod, pars="chill1", summary=FALSE)), digits=2) # 0.02
toughchill2<-round(mean(fixef(toughness.mod, pars="chill2", summary=FALSE)), digits=2) ### -0.05
toughchill2sd<-round(sd(fixef(toughness.mod, pars="chill2", summary=FALSE)), digits=2) # 0.02
toughtxchill1<-round(mean(fixef(toughness.mod, pars="tx:chill1", summary=FALSE)), digits=2) 
toughtxchill1sd<-round(sd(fixef(toughness.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 0.03
toughtxchill1 <- toughtx + toughchill1 + toughtxchill1 ### -0.09

toughtxchill2<-round(mean(fixef(toughness.mod, pars="tx:chill2", summary=FALSE)), digits=2)
toughtxchill2sd<-round(sd(fixef(toughness.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 0.03
toughtxchill2 <- toughtx + toughchill2 + toughtxchill2 ### -0.08

### Thick Model - THICKNESS DECREASES ACROSS ALL CHILL TXs, ESP 4 & 8 wks
thicktx<-round(mean(fixef(thickness.mod, pars="tx", summary=FALSE)), digits=2) ### -8.9
thicktxsd<-round(sd(fixef(thickness.mod, pars="tx", summary=FALSE)), digits=2) # 3.74
thickchill1<-round(mean(fixef(thickness.mod, pars="chill1", summary=FALSE)), digits=2) ### 7.21
thickchill1sd<-round(sd(fixef(thickness.mod, pars="chill1", summary=FALSE)), digits=2) # 6.55
thickchill2<-round(mean(fixef(thickness.mod, pars="chill2", summary=FALSE)), digits=2) ### -8.38
thickchill2sd<-round(sd(fixef(thickness.mod, pars="chill2", summary=FALSE)), digits=2) # 7.48
thicktxchill1<-round(mean(fixef(thickness.mod, pars="tx:chill1", summary=FALSE)), digits=2)
thicktxchill1sd<-round(sd(fixef(thickness.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 5.31
thicktxchill1 <- thicktx + thickchill1 + thicktxchill1 # -3.5

thicktxchill2<-round(mean(fixef(thickness.mod, pars="tx:chill2", summary=FALSE)), digits=2)
thicktxchill2sd<-round(sd(fixef(thickness.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 5.25
thicktxchill2 <- thicktx + thickchill2 + thicktxchill2 ### -15.78

### Ht 60 day Model - Not very intersting, chilling increases growth but nothing with TX
httx<-round(mean(fixef(htdiff.mod, pars="tx", summary=FALSE)), digits=2) # -0.44
httxsd<-round(sd(fixef(htdiff.mod, pars="tx", summary=FALSE)), digits=2) # 0.98
htchill1<-round(mean(fixef(htdiff.mod, pars="chill1", summary=FALSE)), digits=2) ### 2.81
htchill1sd<-round(sd(fixef(htdiff.mod, pars="chill1", summary=FALSE)), digits=2) # 1.55
htchill2<-round(mean(fixef(htdiff.mod, pars="chill2", summary=FALSE)), digits=2) ### 1.32
htchill2sd<-round(sd(fixef(htdiff.mod, pars="chill2", summary=FALSE)), digits=2) # 1.21
httxchill1<-round(mean(fixef(htdiff.mod, pars="tx:chill1", summary=FALSE)), digits=2)
httxchill1sd<-round(sd(fixef(htdiff.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 1.48
httxchill1 <- httx + htchill1 + httxchill1 # 0.36

httxchill2<-round(mean(fixef(htdiff.mod, pars="tx:chill2", summary=FALSE)), digits=2)
httxchill2sd<-round(sd(fixef(htdiff.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 1.46
httxchill2 <- httx + htchill2 + httxchill2 # 0.68

if(FALSE){
### Ht final Model - Not intersting
load("stan/htfinal_brms.Rdata")
httx<-round(mean(fixef(htdiff.mod, pars="tx", summary=FALSE)), digits=2) ### 5.06
httxsd<-round(sd(fixef(htdiff.mod, pars="tx", summary=FALSE)), digits=2) # 4.38
htchill1<-round(mean(fixef(htdiff.mod, pars="chill1", summary=FALSE)), digits=2) # 2.92
htchill1sd<-round(sd(fixef(htdiff.mod, pars="chill1", summary=FALSE)), digits=2) # 4.14
htchill2<-round(mean(fixef(htdiff.mod, pars="chill2", summary=FALSE)), digits=2) ### 11
htchill2sd<-round(sd(fixef(htdiff.mod, pars="chill2", summary=FALSE)), digits=2) # 4.01
httxchill1<-round(mean(fixef(htdiff.mod, pars="tx:chill1", summary=FALSE)), digits=2)
httxchill1sd<-round(sd(fixef(htdiff.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 6.37
httxchill1 <- httx + htchill1 + httxchill1 # -0.42

httxchill2<-round(mean(fixef(htdiff.mod, pars="tx:chill2", summary=FALSE)), digits=2)
httxchill2sd<-round(sd(fixef(htdiff.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 5.49
httxchill2 <- httx + htchill2 + httxchill2 # 4.73
}


### Total biomass Model - TX DECREASES BIOMASS BUT CHILLING CAN COMPENSATE!!!
totbiomasstx<-round(mean(fixef(totbiomass.mod, pars="tx", summary=FALSE)), digits=2) ### -3.45
totbiomasstxsd<-round(sd(fixef(totbiomass.mod, pars="tx", summary=FALSE)), digits=2)  # 2.78
totbiomasschill1<-round(mean(fixef(totbiomass.mod, pars="chill1", summary=FALSE)), digits=2) # 0.38
totbiomasschill1sd<-round(sd(fixef(totbiomass.mod, pars="chill1", summary=FALSE)), digits=2) # 2.91
totbiomasschill2<-round(mean(fixef(totbiomass.mod, pars="chill2", summary=FALSE)), digits=2) # 2.59
totbiomasschill2sd<-round(sd(fixef(totbiomass.mod, pars="chill2", summary=FALSE)), digits=2) # 3.04
totbiomasstxchill1<-round(mean(fixef(totbiomass.mod, pars="tx:chill1", summary=FALSE)), digits=2)
totbiomasstxchill1sd<-round(sd(fixef(totbiomass.mod, pars="tx:chill1", summary=FALSE)), digits=2) #  4.04
totbiomasstxchill1 <- totbiomasstx + totbiomasschill1 + totbiomasstxchill1 # -3.62

totbiomasstxchill2<-round(mean(fixef(totbiomass.mod, pars="tx:chill2", summary=FALSE)), digits=2)
totbiomasstxchill2sd<-round(sd(fixef(totbiomass.mod, pars="tx:chill2", summary=FALSE)), digits=2) #  3.97
totbiomasstxchill2 <- totbiomasstx + totbiomasschill2 + totbiomasstxchill2 # 2.88


### Root to Shoot Model - TX REDUCES ROOT MASS
roottoshoottx<-round(mean(fixef(roottoshoot.mod, pars="tx", summary=FALSE)), digits=2) ### -0.18
roottoshoottxsd<-round(sd(fixef(roottoshoot.mod, pars="tx", summary=FALSE)), digits=2) # 0.15
roottoshootchill1<-round(mean(fixef(roottoshoot.mod, pars="chill1", summary=FALSE)), digits=2) #    -0.03
roottoshootchill1sd<-round(sd(fixef(roottoshoot.mod, pars="chill1", summary=FALSE)), digits=2) # 0.14
roottoshootchill2<-round(mean(fixef(roottoshoot.mod, pars="chill2", summary=FALSE)), digits=2) #    -0.16
roottoshootchill2sd<-round(sd(fixef(roottoshoot.mod, pars="chill2", summary=FALSE)), digits=2) # 0.17
roottoshoottxchill1<-round(mean(fixef(roottoshoot.mod, pars="tx:chill1", summary=FALSE)), digits=2)
roottoshoottxchill1sd<-round(sd(fixef(roottoshoot.mod, pars="tx:chill1", summary=FALSE)), digits=2) # 0.31
roottoshoottxchill1 <- roottoshoottx + roottoshootchill1 + roottoshoottxchill1 # -0.11

roottoshoottxchill2<-round(mean(fixef(roottoshoot.mod, pars="tx:chill2", summary=FALSE)), digits=2)
roottoshoottxchill2sd<-round(sd(fixef(roottoshoot.mod, pars="tx:chill2", summary=FALSE)), digits=2) # 0.23
roottoshoottxchill2 <- roottoshoottx + roottoshootchill2 + roottoshoottxchill2 ### -0.29

@

\section*{Introduction}
% emw-midApril2020: When do you write this up, be careful not to plagiarize yourself. The text needs to be different enough from your other papers (I fin that this can be really hard in methods, but should be do-able in the rest of the text)
\begin{enumerate}
\item The timing of spring in temperate deciduous forests shapes plant and animal communities and influences ecosystem services from agriculture to carbon sequestration to forest management. 
  \begin{enumerate} 
  \item With warming temperatures in the Northern Hemisphere, spring phenology (i.e., budburst and leafout) is advancing.
  \item As budburst and leafout are strongly cued by temperature, species ranges and growing seasons are highly susceptible to change with climate-induced warming \citep{Chuine2001}. % emw-midApril2020: I wondered if it might be good to build on your opening point and maybe follow here by saying: Indeed, forests are leafing out so much earlier that there is discussion about whether early springs could act as important carbon sinks ...Maybe? It feels like some sort of transition might work where you more acknowledge the 'good' advance side and transition to the 'bad' (though of course avoiding all good/bad language).
  \end{enumerate}
  
\item And though the Northern Hemisphere is getting warmer, climate change is affecting general temperature trends but extreme weather events (e.g., polar vortexes) are still occurring. % emw-midApril2020: Nice!
  \begin{enumerate}
  \item These weather events can in turn have big impacts on plant development each spring ... 
  \item One such event is known as a `false spring', which is when temperatures drop below freezing \citep[][i.e., below -2.2$^{\circ}$C]{Schwartz2002} after budburst has initiated.
  \item Just after budburst is initiated is a risky time for plants \citep{Chamberlain2019} and plants can sustain major damage if a frost hits during this time. 
  \item False springs can be very damaging, with reports of trees taking 16-38 days to refoliate after leaf loss from freezing temperatures \citep{Augspurger2009, Augspurger2013, Gu2008, Menzel2015}. 
  \item Such damage can have cascading effects to pollinators \citep{Boggs2012, Pardee2017}, nutrient cycling and carbon uptake as well as forest recruitment \citep{Hufkens2012, Klosterman2018, Richardson2013}
  \item Further, if a false spring occurs and damages a plant, that plant is at an increased risk of experiencing an additional false spring as freezing temperatures can slow the rate of budburst \citep{Augspurger2009} thus ... [there can be big knock-on effects for the ecosystem?]
  \item False springs are predicted to increase in certain regions as climate change progresses, thus understanding the impacts of false springs on forests is essential for forest management strategies and climate forecasting \citep{OBrien2019}.
  \end{enumerate}
  % emw-midApril2020: I re-organized the above to try to 'funnel' the paper more, you want to get your readers interested! A wide breadth of readers too, so early on we want to leave out the complexities that we can (what cues species use, canopy versus understory etc. -- ask yourself if the readers to know this info right now, I think it can wait until they know what (1) what false spring are and (2) why they matter).
  
    % emw-midApril2020: This below paragraph is in a good spot! You set the reader up for climate change and phenology, false springs as an important complicating factor -- and now -- an alternative villain thickens the plot! Warm winters. You just need a transition here for the reader ... something along the lines of 'false springs are not the only thing that may complicate forecasts' or such (depending on how you develop the previous paragraphs)
\item With climate change advancing, chilling is predicted to decrease as winter temperatures warm, potentially impacting phenology and, ultimately, growth. % emw-midApril2020: I would re-write this opening sentence with just warmer winters ... 
  \begin{enumerate}
  \item Warmer winters matter because they impact one of the  three major cues plants use to time budburst: (1) over-winter cold temperatures (chilling), (2) warming spring temperatures (forcing) and (3) longer daylengths (photoperiod). % emw-midApril2020: For the below be sure your readers knows why they need to learn all these dormancy stages ...
  \item Deciduous trees and shrubs require a certain number of chilling hours in order to leave the endodormancy phase \citep{Charrier2011}. 
  \item Endodormancy is the period of winter when temperate trees are inhibited from growing, regardless of the outdoor environment. 
  \item Ecodormancy begins after the chilling requirement has been met and is the period of time when growth can occur but the external environment is not conducive to growth (e.g. too cold) \citep{Basler2012}. 
  \item This two-phase sequence of dormancy helps protect temperate plants against stochastic warm spells in the winter and reduce the risk of a false spring \citep{Basler2014}.% emw-midApril2020: Can you connect the reader back here to why this matters? Just a clause to transition to the next paragraph I think.
  \end{enumerate}

\item Winter warming could impact the quality of budburst \citep{Cleland2007,Bonhomme2010}. % emw-midApril2020: I feel like the point of this paragraph is to convince readers that chilling and false springs may importantly interact, but that is not very clear. Can we make this paragraph's key information more clear? What do the readers need to know to care about and understand your study and what could be skipped or saved for the discussion where you unpack some of the complexity ... 
  \begin{enumerate}
  \item Optimal chilling accumulates between 0$^{\circ}$C to 4$^{\circ}$C, which is also the optimal temperature for starch degradation into sugar accumulation \citep{Tixier2019}.
  \item Sugar accumulation over the winter increases cold hardiness but is also crucial for dormancy break \citep{Tixier2017, Tixier2019}.
  \item Decreases in chilling temperatures from climate change could affect budburst timing \citep{Nanninga2017}, as well as the synchrony of budburst within a population or even within an individual \citep{Sanzperez2009}.
  \item And, reduced chilling---especially if there are fewer cold nights with warming---could impact a plant's tolerance of freezing temperatures throughout the winter \citep{Charrier2011}.
  \item With decreased freezing tolerance, plants are susceptible to damage to leaf tissue, canopy dieback, xylem embolism and injury to the shoot apical meristem, all of which could greatly reduce a plant's ability to recover for the remainder of the growing season or even survive until the next season \citep{Sakai1987,Gu2008}.
  %\item As plants enter dormancy, their vulnerability to freeze damage begins to increase and their cold hardiness (i.e., freezing tolerance) increases. 
  %\item Cold hardiness allows plants to survive freezing temperatures through myriad mechanisms including deep supercooling, increased solute concentration, and an increase in dehydrins or other proteins \citep{Sakai1987, Strimbeck2015}.
  \end{enumerate}
  
  \item Spot for 2-3 additional paragraphs on species differences, community impacts
    \begin{enumerate} % emw-midApril2020: I pulled these points from above as they seemed to specific for how early they were in the intro. I think they could work -- with additional info -- to set up that species are not all the same. From just above the intro could flow: An ideal strategy might thus be to require high chilling, leafout late and avoid frost, but competition between plants puts pressure on individuals to leafout as early as possible and gain priority access to resources ... Thus plants have multiple strategies -- some are late (avoidance), some avoid by speeding through the risky bit (add your info on freezing tolerance), some may try to tolerate .... Then perhaps another paragraph on differences across functional groups and species.
      \item Freezing tolerance in a plant steadily decreases after budburst begins until the leaf is fully unfolded, with leafout being the most susceptible to false spring damage \citep {Lenz2016}.
  \item Thus, temperate plants are at risk of false springs and have evolved to minimize risk through myriad strategies, with the most effective being avoidance: plants must exhibit flexible spring phenologies in order to maximize growth and minimize spring freeze damage by timing budburst effectively.
  \item Seedlings and saplings generally initiate budburst before the canopy trees in order to benefit from the increased light levels \citep {Augspurger2008, Vitasse2013}, which potentially puts understory species and individuals at greater risk \citep{Vitasse2014}.
  \end{enumerate}

\item Here, we assessed the effects of over-winter chilling length and false springs on seedling phenology and growth across ten temperate tree and shrub species. 
  \begin{enumerate}
  \item Individuals were exposed to three levels of over-winter chilling. 
  \item Once budburst was initiated, half of the individuals were exposed to freezing temperatures at -3$^{\circ}$C to mimic a false spring event. 
  \item Individuals were then put in a greenhouse for the remainder of the growing season to ask: (1) How does the accumulation of over-winter chilling hours and (2) how do false spring events impact phenology, physical leaf characteristics and growth?
  \end{enumerate}
\end{enumerate}
  
  %premature budburst
\section*{Methods}
\subsection*{Plant Selection and Material}
\begin{enumerate}
\item We chose 10 temperate woody plant tree and shrub species with varying phenologies, that were not used as crops or ornamental species: \textit{Acer saccharinum} L., \textit{Alnus incana rugosa} L., \textit{Betula papyrifera} Marsh., \textit{Betula populifolia} Marsh., \textit{Cornus racemosa} Lam., \textit{Fagus grandifolia} Ehrh., \textit{Nyssa sylvatica} Marsh., \textit{Salix purpurea} L., \textit{Sorbus americana} Marsh., and \textit{Viburnum dentatum} L.
  \begin{enumerate}
  \item We received 48 dormant bare root seedlings---each measuring 6-12 inches---for each species from Cold Stream Farm LLC (Freesoil, MI; 44$^{\circ}$6' N -86$^{\circ}$12' W) for a total of 480 individuals.
  \item Upon receipt, plants were potted in POT INFO AND SOIL INFO HERE!! and placed in growth chambers at the Weld Hill Research Building of the Arnold Arboretum (Boston, MA; 42$^{\circ}$17' N -71$^{\circ}$8' W) at 4$^{\circ}$C to maintain dormancy.
  \item Two species---\textit{Fagus grandifolia} and \textit{Nyssa sylvatica}---were delivered as root cuttings rather than seedlings and had to be removed from the experiment resulting in eight total species and 384 individuals.
  \item After all individuals had leafed out, all seedlings were up-potted to new pots (NEW POT SIZE HERE) and given fertilizer (FERTILIZER INFO HERE).
  \end{enumerate}
\end{enumerate}
\subsection*{Growth Chamber and Greenhouse Conditions}
\begin{enumerate}
\item Individuals were randomly selected and placed in six experimental treatments: 4 weeks of chilling at 4$^{\circ}$C x no false spring, 4 weeks of chilling at 4$^{\circ}$C x false spring, 6 weeks of chilling at 4$^{\circ}$C x no false spring, 6 weeks of chilling at 4$^{\circ}$C x false spring,
8 weeks of chilling at 4$^{\circ}$C x no false spring, 8 weeks of chilling at 4$^{\circ}$C x false spring.
  \begin{enumerate}
  \item While individuals were in the growth chamber under chilling conditions, photoperiod was mantained at eight hour days.
  \item Lighting within the chambers was provided through a combination of T5HO fluorescent lamps with halogen incandescent bulbs at roughly 250 $\mu mol/m^{2}/s$.
  \item Individuals were rotated within and among growth chambers every two weeks to eliminate possible growth chamber effects.
  \end{enumerate}
\item Once chilling was completed, individuals were moved to a greenhouse with mean daytime temperature of 15$^{\circ}$C and a mean nighttime temperature of 10$^{\circ}$C.
  \begin{enumerate}
  \item Photoperiod was set to 12 hour days throughout the spring until all individuals reached full leaf expansion.
  \item After all individuals reached full leaf expansion, greenhouse temperatures and photoperiods were kept ambient (see Supplemental Materials for more information). 
  \end{enumerate}
\end{enumerate}
\subsection*{Phenology and False Spring Treatment}
\begin{enumerate}
\item Phenology observations were taken every 2-3 days through full leaf expansion and then recorded weekly over the summer.
  \begin{enumerate}
  \item Budburst was denoted as BBCH stage 07, which is `beginning of sprouting or bud breaking' and monitored until full leaf expansion (BBCH stage 19) in order to evaluate the duration of vegetative risk for each individual \citep{Finn2007}.
  \item For the individuals under the `false spring treatment', once at least 50\% of the buds were at BBCH stage 07 but the individual had not yet reached BBCH stage 19, they were placed in a growth chamber set to mimic a false spring event.
  \item Individuals receiving the false spring treatment were placed in a growth chamber for 14 hours, starting at 6pm. 
  \item Temperatures in the growth chamber were ramped down: 6pm to 10$^{\circ}$C, 8pm to 5$^{\circ}$C, 10pm to 0$^{\circ}$C, 12am to -3$^{\circ}$C, 3am to 0$^{\circ}$C, 4am to 5$^{\circ}$C, 6am to 10$^{\circ}$C and 8am temperatures rose again to 15$^{\circ}$C (Figure \ref{fig:gccond}).
  \item After 8am the following day, individuals were collected at placed back in the greenhouse with all of the other plants. 
  \item Once all individuals reached full leaf expansion (BBCH stage 19), phenology observations were made weekly until August 1st, when observations were made every 2-3 days again to monitor fall phenology. 
  \item Individuals were monitored until complete budset, at which point they were harvested for biomass measurements.
  \end{enumerate}
\end{enumerate}
\subsection*{Growth measurements}
\begin{enumerate}
\item Growth was closely measured throughout the entirety of the experiment. 
  \begin{enumerate}
  \item Height was measured three times throughout the growing season: the day an individual reached full leaf expansion, 60 days after full leaf out and when an individual reached complete budset. 
  \item We measured the chlorophyll content of four leaves on each individual 60 days after full leaf out using an atLEAF CHL PLUS Chlorophyll meter (\url{https://www.atleaf.com/atLEAF\_CHL\_PLUS}).
  \item The average chlorophyll content was calculated and then converted to mg/cm\textsuperscript{2} using the atLEAF CHL PLUS conversion tool (\url{https://www.atleaf.com/SPAD}).
  \item We measured leaf thickness using a Shars Digital Micrometer (\url{https://www.shars.com/products\linebreak/measuring/micrometers/0-1-solid-metal-frame-electronic-outside-micrometer}) and leaf toughness in Newtons using a Shimpo Digital Force Gauge (\url{http://shimpoinstruments.com/force\_gauges/fg\-3000}) on two leaves for each individual.
  \item Additionally, we monitored damage to the shoot apical meristem, which consisted of complete damage or disruption of growth in the main stem and resulted in early dormancy induction or reliance on lateral shoot growth.
  \item Finally, belowground and aboveground biomass were harvested after an individual reached complete budset to include leaves in our biomass calculations. 
  \item Belowground and aboveground plant material were separated and then put in a Shel Lab Forced Air Oven (\url{https://www.sheldonmanufacturing.com/shel\-lab\-products/productid/SMO28HP\-2}) at 60$^{\circ}$C for at least 4 days. 
  \end{enumerate}
\end{enumerate}
\subsection*{Data analysis}
\begin{enumerate}
\item Using Bayesian hierarchical models with the brms package \citep{brms}, version 2.3.1,  in R \citep{R}, version 3.3.1, we estimate the effects of chilling duration, false spring treatment and all two-way interactions as predictors on: (1) duration of vegetative risk, (2) growing season length, (3) total growth in centimeters, (4) chlorophyll content, (5) leaf thickness, (6) leaf toughness, (7) shoot apical meristem damage and (8) total biomass. % CUT FOR NOW: and (9) belowground to aboveground biomass ratio. 
  \begin{enumerate} %emw-midApril2020: I would move all equations to the supp as your methods are long already and they are fairly standard equations
  \item Species are modeled hierarchically as grouping factors, which generates an estimate and posterior distribution of the overall response across the eight species used in our experiment.
  \item False spring treatment is written as `tx' in the equation below and chilling was split into two binary predictors: `chill1', which is denoted as `0' for 4 weeks of chilling or `1' for 6 weeks of chilling and `chill2' which is `1' for 8 weeks of chilling:

\begin{align*}
y_i &= \alpha_{species[i]} + \beta_{tx_{species[i]}}X_{tx} + \beta_{chill1_{species[i]}}X_{chill1} + \beta_{chill2_{species[i]}}X_{chill2}\\
&+ \beta_{txchill1_{species[i]}}X_{txchill1} + \beta_{txchill2_{species[i]}}X_{txchill2} + \epsilon_i \tag{1}\\,
\end{align*}
\begin{align*}
\epsilon_i & \sim N(0,\sigma_y) \\
\end{align*}

\item The $\alpha$ and each of the five $\beta$ coefficients are modeled at the species level, as follows:

\begin{align*}
\alpha_{species} & \sim N(\mu_{\alpha}, \sigma_{\alpha}) \\
\beta_{tx_{species}} & \sim N(\mu_{tx}, \sigma_{tx}) \\
\beta_{chill1_{species}} & \sim N(\mu_{chill1}, \sigma_{chill1}) \\
\beta_{chill2_{species}} & \sim N(\mu_{chill2}, \sigma_{chill2}) \\
\beta_{txchill1_{species}} & \sim N(\mu_{txchill1}, \sigma_{txchill1}) \\
\beta_{txchill2_{species}} & \sim N(\mu_{txchill2}, \sigma_{txchill2}) \\
\end{align*}

\item where $i$ represents each unique observation, $species$ is the species, $\alpha$ represents the intercept, $\beta$ terms represent slope estimates, and $y$ is the phenology or growth measurement. 
\item For the shoot apical meristem model, we used a Bernouilli distribution, which is modeled as:

\begin{align*}
 y_i & \sim Binomial(1,p) \tag{2} \\
logit(p) &= \alpha_{species[i]} + \beta_{tx_{species[i]}}X_{tx} + \beta_{chill1_{species[i]}}X_{chill1} + \beta_{chill2_{species[i]}}X_{chill2}\\
&+ \beta_{txchill1_{species[i]}}X_{txchill1} + \beta_{txchill2_{species[i]}}X_{txchill2} + \epsilon_i \nonumber\\,
\end{align*}

\item The $\alpha$ and each of the five $\beta$ coefficients are modeled the same as the other models:

\begin{align*}
\alpha_{species} & \sim N(\mu_{\alpha}, \sigma_{\alpha}) \\
\beta_{tx_{species}} & \sim N(\mu_{tx}, \sigma_{tx}) \\
\beta_{chill1_{species}} & \sim N(\mu_{chill1}, \sigma_{chill1}) \\
\beta_{chill2_{species}} & \sim N(\mu_{chill2}, \sigma_{chill2}) \\
\beta_{txchill1_{species}} & \sim N(\mu_{txchill1}, \sigma_{txchill1}) \\
\beta_{txchill2_{species}} & \sim N(\mu_{txchill2}, \sigma_{txchill2}) \\
\end{align*}

  \item We ran four chains, each with 2 500 warm-up iterations and 4 000 sampling iterations for a total of 6 000 posterior samples for each predictor for each model using weakly informative priors. 
  \item Increasing priors three-fold did not impact our results.
  \item We evaluated our model performance based on $\hat{R}$ values that were close to one and did not include models with divergent transitions in our results. 
  \item We also evaluated high $n_{eff}$ (4000 for most parameters, but as low as 1400 for a couple of parameters in the shoot apical meristem model). 
  \item We additionally assessed chain convergence and posterior predictive checks visually \citep{BDA}.
  \end{enumerate}
\end{enumerate}

\section*{Results}
\begin{enumerate}
\item False springs and chilling durations impacted phenology. 
  \begin{enumerate}
  \item Individuals exposed to the false spring treatment had longer durations of vegetative risk for both the four weeks and six weeks of chilling cohorts (\Sexpr{dvrtx} $\pm$ \Sexpr{dvrtxsd} and \Sexpr{dvrtxchill1} $\pm$ \Sexpr{dvrtxchill1sd}, respectively; Figure \ref{fig:intrxns}a) Figure \ref{fig:mupheno}a) and Table \ref{tab:suppmoddvr}).
  \item Longer chilling treatments reduced the duration of vegetative risk, especially in the 8 weeks of chilling cohort (\Sexpr{dvrchill2} $\pm$ \Sexpr{dvrchill2sd}; Figure \ref{fig:intrxns}a), Figure \ref{fig:muphen}a) and Table \ref{tab:suppmoddvr}).
  \item Additionally, individuals that received eight weeks of chilling did not experience major changes in their durations of vegetative risk (\Sexpr{dvrtxchill2} $\pm$ \Sexpr{dvrtxchill2sd}; Figure \ref{fig:intrxns}a), Figure \ref{fig:muphen}a and Table \ref{tab:suppmoddvr}). 
  \item With increases in chilling duration, the growing season length increased for individuals exposed to six and eight weeks of chilling (\Sexpr{gslengthchill1} $\pm$ \Sexpr{gslengthchill1sd} for six weeks and \Sexpr{gslengthchill2} $\pm$ \Sexpr{gslengthchill2sd} for eight weeks; Figure \ref{fig:intrxns}b), Figure \ref{fig:muphen}b) and Table \ref{tab:suppmodgs}).
  \end{enumerate}
  
\item False springs affected physical leaf traits.
  \begin{enumerate}
  \item Leaf chlorophyll content decreased under false spring conditions, especially in the six weeks (\Sexpr{chltxchill1} $\pm$ \Sexpr{chltxchill1sd}) and eight weeks (\Sexpr{chltxchill2} $\pm$ \Sexpr{chltxchill2sd}; Figure \ref{fig:intrxns}c) Figure \ref{fig:muchl}) and Table \ref{tab:suppmodchl}) of chilling cohorts.
  \item Leaf toughness decreased across all chilling treatments under false spring conditions (\Sexpr{toughtx} $\pm$ \Sexpr{toughtxsd} for four weeks of chilling, \Sexpr{toughtxchill1} $\pm$ \Sexpr{toughtxchill1sd} for six weeks of chilling and \Sexpr{toughtxchill2} $\pm$ \Sexpr{toughtxchill2sd} for eight weeks of chilling; Figure \ref{fig:intrxns}d), Figure \ref{fig:muleaf}a) and Table \ref{tab:suppmodtough}).
  \item Additionally, leaf thickness decreased across all chilling treatments under false spring conditions (\Sexpr{thicktx} $\pm$ \Sexpr{thicktxsd} for four weeks of chilling, \Sexpr{thicktxchill1} $\pm$ \Sexpr{thicktxchill1sd} for six weeks of chilling and \Sexpr{thicktxchill2} $\pm$ \Sexpr{thicktxchill2sd} for eight weeks of chilling; Figure \ref{fig:intrxns}e), Figure \ref{fig:muleaf}b) and Table \ref{tab:suppmodthick}).
  \end{enumerate}
  
\item False springs impacted growth.
  \begin{enumerate}
  \item Across all chilling treatments, individuals exposed to false springs experienced more damage to the shoot apical meristem (\Sexpr{meritx} $\pm$ \Sexpr{meritxsd} for four weeks, \Sexpr{meritxchill1} $\pm$ \Sexpr{meritxchill1sd} for six weeks and \Sexpr{meritxchill2} $\pm$ \Sexpr{meritxchill2sd} for eight weeks; Figure \ref{fig:intrxns}f), Figure \ref{fig:mugrowth}a) and Table \ref{tab:suppmodmeri}) 
  \item Shoot growth for the first 60 days of the growing season increased with increased chilling durations (\Sexpr{htchill1} $\pm$ \Sexpr{htchill1sd} for six weeks of chilling and \Sexpr{htchill2} $\pm$ \Sexpr{htchill2sd} for eight weeks of chilling} except growing did not increase under false spring conditions (\Sexpr{httxchill1} $\pm$ \Sexpr{httxchill1sd} for six weeks and \Sexpr{httxchill2} $\pm$ \Sexpr{httxchill2sd} for eight weeks; Figure \ref{fig:intrxns}g), Figure \ref{fig:muheight}) and Table \ref{tab:suppmodht})).
  \item Individuals exposed to false spring conditions had lower total biomasses when they were exposed to only four weeks of chilling (\Sexpr{totbiomasstx} $\pm$ \Sexpr{totbiomasstxsd}) but there was very little change in total biomass under false spring conditions compared to the control for both the six weeks of chilling cohort (\Sexpr{totbiomasstxchill1} $\pm$ \Sexpr{totbiomasstxchill1sd}) and the eight weeks of chilling cohort (\Sexpr{totbiomasstxchill2} $\pm$ \Sexpr{totbiomasschill2sd}; Figure \ref{fig:intrxns}g), Figure \ref{fig:mugrowth}b) and Table \ref{tab:suppmodtotbio})).
  \end{enumerate}
  
\end{enumerate}

\section*{Discussion}
\begin{enumerate}
\item The effects of chilling and false spring events on phenology: chilling is so important for phenology and can compensate for the detrimental effects of false springs.
  \begin{enumerate}
  \item False springs increase the duration of vegetive risk, leading to an increased risk in multiple false spring risks in one season.
  \item But chilling can compensate for this increase in duration of vegetative risk: if the chilling requirement is met, the rate of budburst does not increase with a false spring event.
  \item This suggests chilling is more important for seedlings in terms of exposure to multiple false springs as well as increased growing season lengths.
  \item With climate change and warming temperatures, over-winter chilling is anticipated to decrease and false springs are predicted to increase in certain regions.
  \item This combination could greatly impact plant performance, survival and shape species distributions, ultimately affecting crucial processes such as carbon uptake and nutrient cycling.
  \end{enumerate}
  
\item False springs greatly impact the physical characteristics of the leaf.
  \begin{enumerate}
  \item With chlorophyll content, leaf toughness and leaf thickness decreasing, the quality of the leaf dwindles.
  \item This reduction in quality could subsequently lead to an increase in herbivory risk (CITE).
  \item Further studies that assess the secondary compounds and total phenolic content (CITE) of the leaves exposed to false springs are needed to better understand the level of herbivory risk. 
  \end{enumerate}
  
\item With sufficient chilling, false springs are less damaging to seedling growth.
  \begin{enumerate}
  \item However, false springs consistently impair shoot apical meristem growth, which can lead to relience on lateral shoot growth, rendering inefficient growth patterns.
  \item Shoot apical meristem damage can lead to potential dieback of seedlings in subsequent growing seasons (CITE). 
  \end{enumerate}
  
\item Understanding the impacts of false springs coupled with reduced over-winter chilling is essential for forecasting.
  \begin{enumerate}
  \item Our findings have large implications for forest recruitment.
  \item With over-winter chilling decreasing with climate change, seedlings are more at risk of sustaining damage from false spring events. 
  \item Understanding recruitment and inter- and intraspecific competition with false springs is crucial. 
  \item If individuals that initiate budburst earlier are more at risk of false spring exposure, this could lead to dieback of early-budbursting species in temperate forests with climate change.
  \end{enumerate}
\end{enumerate}




\bibliography{..//references/chillfreeze.bib}

\section*{Tables and Figures}
  {\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=18cm]{..//analyses/figures/allmsmts.png} 
  -\caption{Interaction plots for all phenology, leaf and growth measurements. }\label{fig:intrxns}
  -\end{center}
  -\end{figure}}
  
  {\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=18cm]{..//analyses/figures/mu_phen.pdf} 
  -\caption{Effects of false spring treatment, six weeks of chilling and eight weeks of chilling on a) duration of vegetative risk and b) growing season length. Dots and lines show means and 50\% uncertainty intervals.}\label{fig:muphen}
  -\end{center}
  -\end{figure}}
  
  {\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=18cm]{..//analyses/figures/mu_leaftraits.pdf} 
  -\caption{Effects of false spring treatment, six weeks of chilling and eight weeks of chilling on a) leaf toughness and b) leaf thickness. Dots and lines show means and 50\% uncertainty intervals. }\label{fig:muleaf}
  -\end{center}
  -\end{figure}}
  
  {\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=18cm]{..//analyses/figures/mu_growth.pdf} 
  -\caption{Effects of false spring treatment, six weeks of chilling and eight weeks of chilling on a) shoot apical meristem damage and b) total biomass. Dots and lines show means and 50\% uncertainty intervals. }\label{fig:mugrowth}
  -\end{center}
  -\end{figure}}
  
  

\end{document}