\documentclass{article}

\begin{document}

\item Optimal chilling accumulates between 0$^{\circ}$C to 4$^{\circ}$C, which is also the optimal temperature for starch degradation into sugar accumulation \citep{Tixier2019}.
  \item Sugar accumulation over the winter increases cold hardiness but is also crucial for dormancy break \citep{Tixier2017, Tixier2019}.
  
    %\item As plants enter dormancy, their vulnerability to freeze damage begins to increase and their cold hardiness (i.e., freezing tolerance) increases. 
  %\item Cold hardiness allows plants to survive freezing temperatures through myriad mechanisms including deep supercooling, increased solute concentration, and an increase in dehydrins or other proteins \citep{Sakai1987, Strimbeck2015}.


\item False springs are not the only things that may complicate forecasts.
  \begin{enumerate}
  \item Winters are warming, which could potentially impact not only phenology but also growth.
  \item Warmer winters directly impact one of the three major cues plants use to time budburst: (1) over-winter cold temperatures (chilling), (2) warming spring temperatures (forcing) and (3) longer daylengths (photoperiod).
  \item Due to harsh winters and unpredictable springs, temperate tree and shrub species have evolved to use a two-phase sequence of dormancy.
  \item The first phase---endodormancy---is the period of winter when temperate trees are inhibited from growing, regardless of the outdoor environment and individuals require a certain number of chilling hours to exit this initial phase \citep{Charrier2011}.
  \item The sceond phase---ecodormancy---begins after the chilling requirement has been met and is the period of time when growth can occur but the external environment is not conducive to growth (e.g. too cold) \citep{Basler2012}. 
  \item With endo- and ecodormancy phases, temperate plants are better protected against stochastic warm spells in the winter and reduce the risk of a false spring \citep{Basler2014} but climate change complicates the timing and depth of dormancy \citep{Charrier2011}.
  \end{enumerate}

\item Winter warming and its effect on dormancy could impact the quality of budburst \citep{Cleland2007,Bonhomme2010}. 
  \begin{enumerate}
  \item Decreases in chilling temperatures from climate change could affect budburst timing \citep{Nanninga2017}, as well as the synchrony of budburst within a population or even within an individual \citep{Sanzperez2009}.
  \item And, reduced chilling---especially if there are fewer cold nights with warming---could impact a plant's tolerance of freezing temperatures throughout the winter \citep{Charrier2011}.
  \item With decreased freezing tolerance, plants are susceptible to damage to leaf tissue, canopy dieback, xylem embolism and injury to the shoot apical meristem, all of which could greatly reduce a plant's ability to recover for the remainder of the growing season or even survive until the next season \citep{Sakai1987,Gu2008}.
  \item Thus, understanding the interplay of warming winters and false spring risk is critical for understanding how temperate forests will change in the future. 
  \end{enumerate}


\end{document}